/**
 * Configuration file for Deepgram API
 * This file should be generated by build process or GitHub Actions
 * to inject the API key from GitHub Secrets
 */

// This will be replaced by GitHub Actions with the actual API key
const DEEPGRAM_CONFIG = {
    apiKey: '${DEEPGRAM_API_KEY}',
    baseUrl: 'https://api.deepgram.com/v1/speak',
    model: 'aura-2-odysseus-en'
};

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = DEEPGRAM_CONFIG;
} else {
    window.DEEPGRAM_CONFIG = DEEPGRAM_CONFIG;
}
