name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create config.js
        run: |
          echo "const config = {" > config.js
          echo "  elevenLabsApiKey: '${{ secrets.ELEVENLABS_API_KEY }}'" >> config.js
          echo "};" >> config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
